### ISSUE TITLE
Default qemu version is out of date

### ISSUE THREAD

**Issue by BijieXu** [Penglai-Enclave/Penglai-Enclave-sPMP#101]
I build the qemu binaries from the "riscv-qemu" path, which generate qemu 4.1.1. when I use this qemu to load the image, it hang up at the output as following
`[Penglai] Penglai Enclave Preparing` 

Then I found in the document that the qemu version should >= 5.2.0. Then I installed the required qemu and it worked ok.

In that case why not removing this "riscv-qemu" from the repo to avoid confusion? Or you can upgrade the qemu into the required one.

**Comment by Ddnirvana** [comment]
@Shang-QY @fengerhu1 Qingyu and Erhu, could you please help to check this issue and help Bijie to fix it?

**Comment by Fly0307** [comment]
Thanks for the suggestion! Currently we are using a newer version than 5.2.0, you can usually just use the latest version of qemu installed or compiled from the [qemu website](https://www.qemu.org/download/) e.g. 8.0.5. We will also replace the version of qemu in the repository in the future.
