### ISSUE TITLE
How to use Penglai Tee-TVM for development?

### ISSUE THREAD

**Issue by JESSIY225** [Penglai-Enclave/Penglai-Enclave-sPMP#105]
Hello, I am very interested in Penglai Tee and would like to conduct research and development on it. But I can only use it to run demo, how should I use it to run my own code? Is there a tutorial available for reference?

**Comment by fengerhu1** [comment]
Hi, JESSIY225 
The doc of Penglai-TVM can be found at https://penglai-doc.readthedocs.io/en/latest/.
As for Penglai-sPMP, it supports the SecGear confidential computing framework. Document is available [here](https://gitee.com/nicolas-cage/secGear/tree/riscv-penglai-zx-dev) (only in Chinese, currently).
We will update an English document for Penglai-sPMP in the github soon!
