### ISSUE TITLE
Unable to run sealdata demo and  others of secgear except helloworld

### ISSUE THREAD

**Issue by SHREEKANT-KUMAR-PRASAD** [Penglai-Enclave/Penglai-Enclave-sPMP#112]
os-openEuler 23.09
kernal-6.4.0
reference document links for demo run
https://github.com/Penglai-Enclave/Penglai-secGear/blob/riscv-penglai-zx-dev/docs/riscv_tee.md
Error which I got during compilation of demos 
[root@openeuler-riscv64 debug]# cmake -DENABLE_ENC_KEY=1 -DCMAKE_BUILD_TYPE=Debug -DENCLAVE=PL -DSDK_PATH=/root/dev/sdk -DSSL_PATH=/root/dev/sdk/penglai_sdk_ssl -DPL_SSLLIB_PATH=/opt/penglai/openssl ..
=============cmake help info=======================
Example default cmd: cmake ..
same with default: cmake -DENCLAVE=SGX -DSDK_PATH=/opt/intel/sgxsdk -DSSL_PATH=/opt/intel/sgxssl ..
cmake [-DCMAKE_BUILD_TYPE=val] [-DENCLAVE=val] [-DCC_SIM=ON] [-DSDK_PATH=path] [-DSSL_PATH=path] ..
CMAKE_BUILD_TYPE:[optional] pass Debug if you need file line info in log, default log without file line
ENCLAVE:[optional] valid val: SGX --default, GP --trustzone, PL --Penglai
CC_SIM:[optional] only support by SGX
SDK_PATH:[optional] default SGX:/opt/intel/sgxsdk, GP:/opt/itrustee_sdk, PL:/root/dev/sdk;
	 pass SDK_PATH if you installed sdk in custom path
SSL_PATH:[optional] pass security ssl installed path when your application use ssl
=============cmake help info=======================
Current Platform: RISC-V, Penglai SDK PATH:/root/dev/sdk
CMake Error at examples/seal_data/enclave/CMakeLists.txt:155 (set_target_properties):
  set_target_properties Can not find target to add properties to: seal_data

CMake Error at examples/seal_data/host/CMakeLists.txt:69 (target_link_libraries):
  Cannot specify link libraries for target "secgear_seal_data" which is not
  built by this project.

-- Configuring incomplete, errors occurred!
See also "/root/dev/secGear/debug/CMakeFiles/CMakeOutput.log".

thanks 
shreekant
![secgeardemoissue](https://github.com/Penglai-Enclave/Penglai-Enclave-sPMP/assets/158438609/0967722a-f1eb-4334-858f-6458109116ce)

**Comment by Fly0307** [comment]
Sorry, but when I put the contents of the **sdk** and **secGear** directories locally in the ~/dev/sdk and ~/dev/secGear directories respectively and execut the following command to compile does not prompt the above problem:
```
# using the pre-compiled sdk toolkit https://ipads.se.sjtu.edu.cn:1313/d/6a464e02cd3d4c1bafb0/ and install penglai-ssl-2.10-1.riscv64.rpm
cd ~/dev
cd sdk
vim demo/Makefile #comment evm and evm/host
PENGLAI_SDK=$(pwd) make -j$(nproc)

cd ~/dev/secGear
mkdir debug

cmake -DENABLE_ENC_KEY=1 -DCMAKE_BUILD_TYPE=Debug -DENCLAVE=PL -DSDK_PATH=/root/dev/sdk -DSSL_PATH=/root/dev/sdk/penglai_sdk_ssl -DPL_ SSLLIB_PATH=/opt/penglai/openssl ..
make -j$(nproc)
make install
```

If you still fail to run the demo, please provide more detailed log messages or run instructions so that we can find the problem.

**Comment by SHREEKANT-KUMAR-PRASAD** [comment]
Thanks for the comment but In my penglai sdk I am not geeting this folder penglai_sdk_ssl .

**Comment by SHREEKANT-KUMAR-PRASAD** [comment]
Thanks for your solution but in my penglai SDK I  am not getting
penglai_sdk_ssl. Can you tell me about this issue?
Thanks & Regards
Shreekant

**Comment by SHREEKANT-KUMAR-PRASAD** [comment]
can you help me  to locate penglai_sdk_ssl.

**Comment by SHREEKANT-KUMAR-PRASAD** [comment]
someone look into my issue please

**Comment by Fly0307** [comment]
> can you help me to locate penglai_sdk_ssl.

Download link : https://ipads.se.sjtu.edu.cn:1313/d/6a464e02cd3d4c1bafb0/

In the package **penglai_secGear_env.tar.gz** you will find the directory _sdk/penglai_sdk_ssl_, which has the same contents as penglai-ssl-2.10-1.riscv64.rpm installed in _/opt/penglai/openssl._

**Comment by abhi-84** [comment]
Sorry, but penglai_sdk_ssl directory is not located inside the penglai_secGear_env.tar.gz. Can you please check and reconfirm!

![image](https://github.com/Penglai-Enclave/Penglai-Enclave-sPMP/assets/10266522/ad78b63d-9365-430a-87d7-8bb525998ed5)

**Comment by SHREEKANT-KUMAR-PRASAD** [comment]
![Screenshot from 2024-03-03 23-07-25](https://github.com/Penglai-Enclave/Penglai-Enclave-sPMP/assets/158438609/741a85eb-40c1-4abb-9ce7-7262b21aca40)

Hi
[Fly0307](https://github.com/Fly0307),

Sorry, but I aslo not getting the penglai_sdk_ssl directory in the penglai_secgear_env.tar.gz which I downloaded from the above suggested link.So please look into this .

**Comment by Fly0307** [comment]
> ![Screenshot from 2024-03-03 23-07-25](https://private-user-images.githubusercontent.com/158438609/309568876-741a85eb-40c1-4abb-9ce7-7262b21aca40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3OTkzNjgsIm5iZiI6MTcwOTc5OTA2OCwicGF0aCI6Ii8xNTg0Mzg2MDkvMzA5NTY4ODc2LTc0MWE4NWViLTQwYzEtNGFiYi05Y2U3LTcyNjJiMjFhY2E0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QwODExMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NGIwNDIwMTM5NzBlYjk1OGQwZDk1NTdmYzY5OTMyOGViYjAxMjc2Yzk3NjliYzhiODM4ODRiMWQxODBiZDVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7aLd8PIt5g_9dEBhLLl46K38tLCYYdPCZ0GHyF3pTg4)
> 
> Hi [Fly0307](https://github.com/Fly0307),
> 
> Sorry, but I aslo not getting the penglai_sdk_ssl directory in the penglai_secgear_env.tar.gz which I downloaded from the above suggested link.So please look into this .

Sorry, we have updated the latest link containing the penglai_sdk_ssl directory zip package ： https://ipads.se.sjtu.edu.cn:1313/f/96aa0496d47441d6824d/
<img width="886" alt="image" src="https://github.com/Penglai-Enclave/Penglai-Enclave-sPMP/assets/92023558/f9c7e955-76b9-4f98-99ba-b7c6a6eb861d">

**Comment by SHREEKANT-KUMAR-PRASAD** [comment]
![Uploading secgearlookingmysqlclientlib.png…]()
Hi fly,
can you have any reference documents regarding MySQL database connectivity with sec gear.
I have tried some attempt to connect to mysql database but its fail,so I am sharing A screenshot of my output attached  below 

![Uploading image.png…]()


issue: its seems that mysql library is not accessable to secgear while buliding the database connectivity code.
thanks 
shreekant
