### ISSUE TITLE
Nuclei SDK should be renamed to Nuclei Linux SDK

### ISSUE THREAD

**Issue by fanghuaqi** [Penglai-Enclave/Penglai-Enclave-sPMP#72]
Nuclei SDK is mainly for baremetal/rtos environment development.
Nuclei Linux SDK is for risc-v linux environment development.

So https://github.com/Penglai-Enclave/Penglai-Enclave-sPMP/blob/opensbi/README.md?plain=1#L26  should be 

~~~
[Nuclei Linux SDK](https://github.com/Nuclei-Software/nuclei-linux-sdk/tree/dev_flash_penglai_spmp).
~~~

**Comment by Ddnirvana** [comment]
@fanghuaqi Thanks for pointing out the issue. The PR #73 fix the issue.
